# Generated YAML configuration example
# Service name for telemetry and logs
service_name: exitgatebot

sentry:
  dsn: "https://a1b2c3d4e5f6g7h8a1b2c3d4e5f6g7h8@o123456.ingest.sentry.io/1234567"

log:
  # Telegram logging config
  telegram:
    # Chat bot token, obtain it via BotFather
    token: "1234567890:ABCdefGHIjklMNopQRstUVwxyZ-123456789"

    # Chat ID to send messages to
    chat_id: 1001234567890

telemetry:
  # Whether to enable opentelemetry logs/metrics/traces export
  enabled: true

twitch:
  # ClientID of the twitch application
  client_id: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p

  # Client secret of the twitch application
  client_secret: abc123def456ghi789jkl012mno345pqr678stu901

  # Username of the bot account
  username: PogChamp123

  # User refresh token of the bot account
  refresh_token: v1.abc123def456ghi789jkl012mno345pqr678stu901vwx234yz567

  # Disable notifications
  disable_notifications: true

steam:
  # Check interval in minutes
  check_interval: 10

openai:
  # OpenAI base url
  base_url: "https://bothub.chat/api/v2/openai/v1"

  # OpenAI token
  token: "sk-proj-abc123456789DEF789ghi012JKL345mno678PQR901stu234VWX"

  # OpenAI model
  model: "deepseek-v3.2-exp"

profiles:
  - steam_link: "https://steamcommunity.com/id/Maznevich"
    username: maznevich
